### ISSUE TITLE
Image format & batch processing

### ISSUE THREAD

**Issue by ear1grey** [pompeybug/website#42]
For bandwidth minimisation & speed we should probably to a single format (probably AVIF).  This can be done once now, but what about for new articles?  Perhaps a tool integrated into the build process that can scan each story for assets, and if they're jpg, convert them automatically.

Options then would include (a) only publishing the avif version or (b) publishing avif AND the original and using the `<picture>` element to allow the UA to select.

**Comment by MiniCheese26** [comment]
This is handled by Astro's image optimisation systems, every image is converted to a webp given it's imported properly (which we've discussed)
